config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "grams#index"
  resources :grams do
    resources :comments, only: [:create]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :gram

  validates :comment, presence: true
end

app/models/gram.rb
class Gram < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  mount_uploader :image, ImageUploader

  validates :caption, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :grams
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    return render_404 if current_gram.blank?
    current_gram.comments.create(comment_params.merge(user: current_user))
    redirect_to gram_path(current_gram)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

  def render_404
    render text: 'Not found', status: :not_found
  end

  helper_method :current_gram
  def current_gram
    @current_gram ||= Gram.find_by_id(params[:gram_id])
  end

end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @grams = Gram.order(:created_at).reverse_order
  end

  def new
    @gram = Gram.new
  end

  def create
    @gram = current_user.grams.create(gram_params)
    return redirect_to root_path if @gram.valid?
    render :new, status: :unprocessable_entity
  end

  def show
    return render_status(:not_found) if current_gram.blank?
    @comment = Comment.new
  end

  def edit
    return render_status(:not_found) if current_gram.blank?
    return render_status(:forbidden) if current_user != current_gram.user
    @gram = current_gram
  end

  def update
    return render_status(:not_found) if current_gram.blank?
    return render_status(:forbidden) if current_user != current_gram.user
    current_gram.update_attributes(gram_params)
    return redirect_to root_path if current_gram.valid?
    render :edit, status: :unprocessable_entity
  end

  def destroy
    return render_status(:not_found) if current_gram.blank?
    return render_status(:forbidden) if current_user != current_gram.user
    current_gram.destroy
    redirect_to root_path
  end

  private

  def gram_params
    params.require(:gram).permit(:caption, :image)
  end

  def render_status(status)
    render text: "#{status.to_s.titleize}", status: status
  end

  helper_method :current_gram
  def current_gram
    @current_gram ||= Gram.find_by_id(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/views/grams/_gramform.html.erb
<%= simple_form_for gram do |f| %>
  <div class="file-field input-field">
    <a class="btn waves-effect waves-light">
      <i class="material-icons left">file_upload</i>
      Image
      <%= f.input :image, label: false %>
    </a>
    <div class="file-path-wrapper">
      <input class="file-path validate" type="text">
    </div>
  </div>
  <%= f.input :caption, label: false, placeholder: 'Add a caption...', input_html: {class: "materialize-textarea"} %>
  <%= f.button :button, cta, class: "waves-effect waves-light btn right" %>
<% end %>

app/views/grams/edit.html.erb
<h3>Edit Post</h3>

<%= render partial: "grams/gramform", locals: {gram: @gram, cta: "Save Changes"} %>

app/views/grams/index.html.erb
<br>
<% @grams.each do |gram| %>
  <div class="row user-header">
    <div class="valign-wrapper col s12">
      <i class="material-icons">account_circle</i>
      <span class="username">
        <b><%= gram.user.email %></b>
      </span>
    </div>
  </div>
  <%= link_to gram_path(gram) do %>
    <%= image_tag gram.image, class: 'responsive-img' %>
  <% end %>

  <div class="valign-wrapper">
    <span><b><%= gram.user.email %></b>&nbsp;<%= gram.caption %></span>
  </div>

  <div class="comments">
    <% if gram.comments.count > 2 %>
      <%= link_to gram_path(gram) do %>
        <span class="view-all-comments">View all <%= gram.comments.count %> comments</span>
      <% end %>
    <% end %>
    <% gram.comments.order(:created_at).last(2).each do |comment| %>
      <div>
        <b><%= comment.user.email %></b>
        <%= comment.comment %>
      </div>
    <% end %>
  </div>
  <br>
<% end %>

app/views/grams/new.html.erb
<h3>New Post</h3>

<%= render partial: "grams/gramform", locals: {gram: @gram, cta: "Share"} %>

app/views/grams/show.html.erb
<br>
<div class="row user-header">
  <div class="col s10 m11 valign-wrapper">
    <i class="material-icons">account_circle</i>
    <span class="username">
      <b><%= current_gram.user.email %></b>
    </span>
  </div>

  <div class="col s2 m1 valign-wrapper">
    <% if current_user == current_gram.user %>
      <%= link_to  edit_gram_path(current_gram) do %>
        <i class="material-icons right deep-orange-text text-accent-2">edit</i>
      <% end %>
    <% end %>
  </div>

</div>

<%= image_tag current_gram.image, class: 'responsive-img' %>

<div class="row comment valign-wrapper">
  <div class="col s1">
    <i class="material-icons valign">account_circle</i>
  </div>
  <div class="col s11">
    <b><%= current_gram.user.email %></b>
    <br>
    <%= current_gram.caption %>
  </div>
</div>

<div class="comments-list">
  <% current_gram.comments.each do |comment| %>
    <div class="row comment valign-wrapper">
      <div class="col s1">
        <i class="material-icons valign">account_circle</i>
      </div>
      <div class="col s11">
        <b><%= comment.user.email %></b>
        <br>
        <%= comment.comment %>
      </div>
    </div>
  <% end %>
</div>

<div class="new-comment">
  <%= simple_form_for @comment, url: gram_comments_path(current_gram) do |f| %>
    <div class="row valign-wrapper">
      <div class="col s1">
      </div>
      <div class="col s8">
        <%= f.input :comment, label: false, placeholder: 'Add a comment...', input_html: {class: "materialize-textarea valign" } %>
      </div>
      <div class="col s3">
        <%= f.button :button, "Post", class: "waves-effect waves-light btn btn-flat deep-orange-text text-accent-2 right submit-link valign" %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_navlinks.html.erb
<% if !user_signed_in? %>
  <li>
    <%= link_to "Sign up", new_user_registration_path %>
  </li>
  <li>
    <%= link_to "Sign in", new_user_session_path %>
  </li>
<% else %>
  <li>
    <%= link_to "New Post", new_gram_path %>
  </li>
  <li>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pixify</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <div class="nav-wrapper container">
    <%= link_to "Pixify", root_path, class: "brand-logo" %>
    <a data-activates="mobile-nav" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <%= render partial: "layouts/navlinks" %>
    </ul>
    <ul id="mobile-nav" class="side-nav">
      <%= render partial: "layouts/navlinks" %>
    </ul>
  </div>
</nav>

<main class="container">
<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->
<%= yield %>
</main>


</body>
</html>